### ISSUE TITLE
Do I really need to create a new Instance of ModelMapper for each conversion?

### ISSUE THREAD

**Issue by WellMafra** [jhalterman/modelmapper#140]
I tried to keep just one instance, using a static attribute of ModelMapper, but when I pass a List with 2 distinct items, it returns 2 identical items, being that, both items are the result of the first conversion. I guess that ModelMapper is keeping state

**Comment by jhalterman** [comment]
You can use separate ModelMapper instances for this, or separate named TypeMaps:

```
ModelMapper.createTypeMap(Foo.class, FooDTO.class, "simple");
FooDTO dto = modelMapper.map(foo, FooDTO.class, "simple");
```

**Comment by WellMafra** [comment]
I think that I need something else. Bellow is my example, in this case, I have a list of FooDto and I need to make a faster conversion, so I kept the instance of ModelMapper with a static field.

```java
public class FooResource {

	public Response save(List<FooDto> listFooDto) {
		...
		List<Foo> listFoo = new FooMapper().fromDTO(listFooDto);
		...
	}
}
```

```java
public class FooMapper {

    private static ModelMapper modelMapper;
    private BarMapper barMapper;
    
    public Foo fromDTO(FooDto dto) {
        Foo entity = createModelMapper().map(dto, Foo.class);
        entity.setListBar(getBarMapper().fromListDTO(listBarDto))
        return entity;
    }

    private ModelMapper createModelMapper() {
        PropertyMap<FooDto, Foo> fooMap = new PropertyMap<FooDto, Foo>() {
            @Override
            protected void configure() {
                map().setId(new FooId());
                map().getId().setNetCode(source.getNetCode());
                map().getId().setFooCode(source.getFooCode());
                map().setListBar(null);
            }
        };
        modelMapper = new ModelMapper();
        modelMapper.addMappings(fooMap);
        return modelMapper;
    }

    private BarMapper getBarMapper() {
        if (barMapper == null) {
            barMapper = new BarMapper();
        }
        return barMapper;
    }
    
    private ModelMapper getModelMapper() {
        if (modelMapper == null) {
            modelMapper = new ModelMapper();
        }
        return modelMapper;
    }
}
```

**Comment by WellMafra** [comment]
I fixed that!
It was my fault, The reason is that I was setting:
```java
 map().setId(new FooId());
```
And this way it was keeping the reference in the memory, and so, because of that, It was duplicating the register.

**Comment by ffradegrada** [comment]
@jhalterman i ended in this issue because i was looking for something else, but your answer fix perfectly my doubts! I think that model mapper documentation is poor, but it's an amazing tool.

Thanks!

**Comment by jhalterman** [comment]
@ffradegrada The docs could certainly use improvements. Would love to hear suggestions if you have any. The docs repository is also on github so pull requests are welcome!

https://github.com/modelmapper/modelmapper.github.io
