### ISSUE TITLE
Causes error with eclipselink metamodel processor

### ISSUE THREAD

**Issue by ChristophGr** [jhalterman/modelmapper#141]
error: com.sun.tools.javac.code.Symbol$CompletionFailure: class file for org.modelmapper.internal.cglib.reflect.FastClass not found

**Comment by jhalterman** [comment]
Hi @ChristophGr - Can you give some more info on what you'd doing to hit this? I want to make sure that adding another 30k of classfiles to the modelmapper jar is necessary before doing so.

**Comment by ChristophGr** [comment]
I have some JPA-entities in my project, and I want to generate metamodel-classes for them. This is done by an Annotation-processor, that runs during compile. As soon as I add any reference to ModelMapper to the source-code (like calling new ModelMapper()), the java-compiler throws the error above.

**Comment by jhalterman** [comment]
Thanks for filing this.
