### ISSUE TITLE
Cannot map final method

### ISSUE THREAD

**Issue by haidelber** [jhalterman/modelmapper#148]
I try to map `org.hibernate.validator.internal.engine.ConstraintViolationImpl.getMessage()` to a custom classes property.

I use following mapping:
```java
map().setMessageKey(this.source.getMessage());
```

As described in [Hibernate Validator Javadoc](https://docs.jboss.org/hibernate/validator/5.1/api/index.html?org/hibernate/validator/internal/engine/ConstraintViolationImpl.html) the method itself is final. Is it possible to use ModelMapper in this scenario? Am I missing something?

**Comment by jhalterman** [comment]
@haidelber This is actually a limitation of ModelMapper, unfortunately. In order for the mapping API to work, it proxies (via a subclass) the source and destination types. Since final methods cannot be subclassed these methods cannot be mapped.

**Comment by haidelber** [comment]
Thanks for the fast response.. In fact I found a workaround in the meanwhile as it is fortunately working with implicit mapping. I just had to rename the fields of the destination class.
